
//
//  UsersData.swift
//
//
//  Generated by Nico Koelewijn on 19/05/15.
//  Copyright (c) 2015 Nico Koelewijn. All rights reserved.
//

import UIKit

class UsersData: NSObject, NSCoding {
        let id: Int
		let name: String
		let partner_id: Int
        let partner_found: Int
        let fav_stage: String
        let fav_genre: String
		

    init(id:Int, name:String, partner_id:Int, partner_found:Int, fav_stage:String, fav_genre:String){
        self.id = id
        self.name = name
        self.partner_id = partner_id
        self.partner_found = partner_found
        self.fav_stage = fav_stage
        self.fav_genre = fav_genre
		
    }

    override var description:String{
        return "[UsersData] \(id), \(name), \(partner_id), \(partner_found), \(fav_stage), \(fav_genre)"
    }
    
    func encodeWithCoder(aCoder: NSCoder) {
        aCoder.encodeObject(id, forKey:"id")
        aCoder.encodeObject(name, forKey:"name")
        aCoder.encodeObject(partner_id, forKey:"partner_id")
        aCoder.encodeObject(partner_found, forKey:"partner_found")
        aCoder.encodeObject(fav_stage, forKey:"fav_stage")
        aCoder.encodeObject(fav_genre, forKey:"fav_genre")
    }
    
    required init(coder aDecoder: NSCoder) {
        id = aDecoder.decodeObjectForKey("id") as! Int
        name = aDecoder.decodeObjectForKey("name") as! String
        partner_id = aDecoder.decodeObjectForKey("partner_id") as! Int
        partner_found = aDecoder.decodeObjectForKey("partner_found") as! Int
        fav_stage = aDecoder.decodeObjectForKey("fav_stage") as! String
        fav_genre = aDecoder.decodeObjectForKey("fav_genre") as! String
        super.init()
    }
    
}